import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { DynamicListProvider } from '../DynamicListContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AppSimulador',
  description: 'Generated by @DevEd',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicListProvider>
          <Providers>
            {children}
          </Providers>
        </DynamicListProvider>
      </body>
    </html>
  )
}
